/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        base: 'var(--color-bg-root)',
        panel: 'var(--color-bg-panel)',
        elevated: 'var(--color-bg-elevated)',
        glass: 'var(--color-bg-glass)',
        'glass-hover': 'var(--color-bg-glass-hover)',
        border: 'var(--color-border)',
        'border-subtle': 'var(--color-border-subtle)',
        primary: 'var(--color-text-primary)',
        secondary: 'var(--color-text-secondary)',
        tertiary: 'var(--color-text-tertiary)',
        muted: 'var(--color-text-muted)',
        emerald: 'var(--color-emerald)',
        amber: 'var(--color-amber)',
        violet: 'var(--color-violet)',
        rose: 'var(--color-rose)',
        blue: 'var(--color-blue)',
        cyan: 'var(--color-cyan)',
      },
      fontFamily: {
        heading: ['var(--font-heading)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      boxShadow: {
        'macos-sm': 'var(--shadow-macos-sm)',
        'macos-md': 'var(--shadow-macos-md)',
        'macos-lg': 'var(--shadow-macos-lg)',
        'macos-xl': 'var(--shadow-macos-xl)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      spacing: {
        4: 'var(--space-4)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
        48: 'var(--space-48)',
        64: 'var(--space-64)',
        80: 'var(--space-80)',
      },
      transitionTimingFunction: {
        spring: 'var(--ease-spring)',
        fluid: 'var(--ease-fluid)',
        snappy: 'var(--ease-snappy)',
      },
    },
  },
  plugins: [],
}
